(add-to-list 'load-path (concat user-emacs-directory "lisp/"))

(require 'rod-ui)
(require 'rod-bootstrap)
(require 'rod-performance)
(require 'rod-env)
(require 'rod-session)
(require 'rod-git)
(require 'rod-qol)
(require 'rod-backup)
(require 'rod-dired)
(require 'rod-minibuffer)
(require 'rod-completion)
(require 'rod-workspace)
(require 'rod-search)
(require 'rod-js)
(require 'rod-ts)
(require 'rod-project)
(require 'rod-md)
(require 'rod-programming)
(require 'rod-profiling)
(require 'rod-diff)
(require 'rod-lsp)
(require 'rod-service)
(require 'rod-command)
(require 'rod-org)
(require 'rod-info)
